name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint PyQt6 psutil requests
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=C0103,C0111,C0301,C0302,C0325,C0326,C0330,C0411,C0412,C0413,C0414,C0415,W0401,W0611,W0612,W0613,W0614,W0703,R0901,R0902,R0903,R0904,R0911,R0912,R0913,R0914,R0915,E1101
